import pandas as pd
import numpy as np
#practice of both pand and numpy
b=np.ones((6,5))
print(b)
#print(b[2:4,0:2])
list1=[0,4,5]
list2=[3]
#print(b[list1,list2])
print(b[[0,4,5],3:])

a=np.zeros((2,3))
print(a)
c=np.ones((3,3))
print(c)
e=np.array([1,2,3,4,5,2,3,4,4,5])
f=e.reshape(10,1)
print(f.shape)
g=f.astype('int32')
print(g.size)
d=np.genfromtxt('emp.txt',delimiter=',',dtype='int32')
print(d[d>55])
h=np.full((3,2),33)
print(h)
i=np.full_like(f,44)
print(i)
k=np.random.rand(3,2)
print(k)
l=np.random.randint(5,10,size=(2,3))
print(l)
m=np.random.random_sample(e.shape)
print(m)
o=np.repeat(e,4,axis=1)
print(o)
p=np.zeros((1,2))
q=np.ones((2,1))
print(np.matmul(p,q))
r=np.random.default_rng()#used for integer and shuffle
s=r.integers(low=1,high=6,size=(3,3))
print(s)
np.random.seed(seed=1)
u=np.random.uniform(low=1,high=4,size=(2,2))
print(u)
r.shuffle(e)
print(e)