ALTER TABLE employee ADD CONSTRAINT UNIQUE KEY(super_id);
ALTER TABLE employee MODIFY name VARCHAR( 10);
ALTER TABLE employee ADD CONSTRAINT herum CHECK (salary > 1000);
ALTER TABLE employee DROP COLUMN ram; SO GROUP BY EXAMP MA CHAI JAILE FRIST MA DIVIDE GARXA EXAMP ANI EUATI ROW MA NIKALXA DIFFERENT RESULT AAYO VANEY ERROR FALXA
SO ANI HAVING USE GARNEY BELA CHAI GROUP BY MA VAKO MATRA USE GARNA MILXA